# Generated by Django 4.1.7 on 2023-03-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
        migrations.AddField(
            model_name='course',
            name='course_days_of_week',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_end_time',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_start_time',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
