name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python3 -m venv ~/.virtualenvs/djangodev
        source ~/.virtualenvs/djangodev/bin/activate
        python -m pip install Django
        git clone https://github.com/django/django.git
        python -m pip install -e django/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install django-bootstrap-v5
    - name: Run Tests
      run: |
        python manage.py test --keepdb
